"""initial migration

Revision ID: 82ed5f89b639
Revises: 
Create Date: 2026-07-24 12:28:56.291560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ed5f89b639'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_phone'), 'registrations', type_='unique')
    op.create_index(op.f('ix_registrations_phone'), 'registrations', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_phone'), table_name='registrations')
    op.create_unique_constraint(op.f('unique_phone'), 'registrations', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
